checkpoints:
  checkpoint_interval: 500
  checkpoints_path: /leonardo_scratch/large/userexternal/tbonomo0/longctx_checkpoints/quick_warmup_run_20260107/
  checkpoints_path_is_shared_file_system: true
  load_lr_scheduler: true
  load_optimizer: true
  resume_checkpoint_path: /leonardo_scratch/large/userexternal/tbonomo0/longctx_checkpoints/quick_warmup_run_20260107/8000
  save_final_state: true
  save_initial_state: false
data_stages:
- data:
    dataset:
      dataset_folder:
      - /leonardo_scratch/fast/FAIR_NLP/minerva/data_128k_continual/tkn/cpt/it/testimole-books # 0.26 B
      - /leonardo_scratch/fast/FAIR_NLP/minerva/data_128k_continual/tkn/cpt/it/itagutenberg # 0.13 B
      - /leonardo_scratch/fast/FAIR_NLP/minerva/data_128k_continual/tkn/cpt/it/redpajamav2/2023-14 # 3.48 B
      - /leonardo_scratch/fast/FAIR_NLP/minerva/data_128k_continual/tkn/cpt/en/fineweb # 4.35 B
      - /leonardo_scratch/fast/FAIR_NLP/minerva/data_128k_continual/tkn/cpt/en/the_stack # 2.54 B
      - /leonardo_scratch/fast/FAIR_NLP/minerva/data_128k_continual/tkn/cpt/en/wikipedia # 7.12 B
      - /leonardo_scratch/fast/FAIR_NLP/minerva/data_128k_continual/tkn/cpt/it/wikipedia # 1.23 B
      - /leonardo_scratch/fast/FAIR_NLP/minerva/data_128k_continual/tkn/cpt/en/dolmino_math # 0.62 B
      - /leonardo_scratch/fast/FAIR_NLP/minerva/data_128k_continual/tkn/cpt/en/dolmino_stackexchange # 1.51 B
      - /leonardo_scratch/fast/FAIR_NLP/minerva/data_128k_continual/tkn/cpt/it/gazzetta # 1.71 B
      - /leonardo_scratch/fast/FAIR_NLP/minerva/data_128k_continual/tkn/cpt/en/flan_filtered # 13.45 B
      - /leonardo_scratch/fast/FAIR_NLP/minerva/data_128k_continual/tkn/cpt/en/project_gutenberg # 6.36 B
      - /leonardo_scratch/fast/FAIR_NLP/minerva/data_128k_continual/tkn/cpt/it/finepdfs # 7.28 B
      - /leonardo_scratch/fast/FAIR_NLP/minerva/data_128k_continual/tkn/cpt/en/finepdfs # 19.12 B
      dataset_max_tokens: null
      dataset_read_path: null
      dataset_weights: # proportional to size
      - 0.52 # testimole-books 0.26 B x2 
      - 0.26 # itagutenberg 0.13 B x2 
      - 3.48 # redpajamav2/2023-14 3.48 B
      - 4.35 # fineweb EN 4.35 B
      - 2.54 # the_stack 2.54 B
      - 7.12 # wikipedia EN 7.12 B
      - 2.46 # wikipedia IT 1.23 B x2
      - 0.62 # dolmino_math 0.62 B
      - 1.51 # dolmino_stackexchange 1.51 B
      - 1.71 # gazzetta 1.71 B
      - 13.45 # flan_filtered 13.45 B
      - 6.36 # project_gutenberg EN 6.36 B
      - 14.56 # finepdfs IT 7.28 B x2
      - 10 # finepdfs EN 19.12 B scaled down
      pad_samples_to_global_batch_size: true # Avoid issues with DDP at last step
      return_positions: true
      shuffle_files: true
      skip_in_stream: false
      token_size_in_bytes: 2
      tokenizer_name: /leonardo_scratch/large/userexternal/tbonomo0/models/sapienzanlp--Minerva-7B-base-recipe2
      use_old_brrr_dataloader: false
      vocab_size: 51200
    num_loading_workers: 1
    seed: 204
  name: Stable Training Stage
  sequence_length: 131072 # 65536
  start_training_step: 1
general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: false
  project: resume_training
  run: resume_training_20251217_134959_local
  seed: 204
  step: null
lighteval: null
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
metrics_logging: null
model:
  ddp_bucket_cap_mb: 25
  dtype: bfloat16
  init_method:
    scaling_method: NUM_LAYERS
    std: 0.025
  make_vocab_size_divisible_by: 1
  model_config:
    _attn_implementation: llama3_ring_attention
    ring_attn_heads_k_stride: 1
    _use_doc_masking: true
    attention_bias: false
    bos_token_id: 1
    eos_token_id: 2
    flex_attention_mask: null
    hidden_act: silu
    hidden_size: 4096
    initializer_range: 0.02
    intermediate_size: 14336
    is_mistral_config: true
    max_position_embeddings: 131072 # 65536
    num_attention_heads: 32
    num_hidden_layers: 32
    num_key_value_heads: 8
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-05
    rope_interleaved: false
    rope_theta: 1500000.0
    sliding_window_size: null
    tie_word_embeddings: false
    use_cache: false
    vocab_size: 51200
optimizer:
  accumulate_grad_in_fp32: true
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.0002
    lr_decay_starting_step: 300
    lr_decay_steps: 16435
    lr_decay_style: linear
    lr_warmup_steps: 300
    lr_warmup_style: linear
    min_decay_lr: 0
  optimizer_factory:
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    name: adamW
    torch_adam_is_fused: true
  weight_decay: 0.01
  weight_decay_exclude_named_params: []
  zero_stage: 0
parallelism:
  context_parallel_size: 4
  dp: 8
  expert_parallel_size: 1
  pp: 1
  pp_engine: 1f1b
  recompute_layer: true
  tp: 4
  tp_linear_async_communication: true
  tp_mode: REDUCE_SCATTER
  tp_recompute_allgather: true
profiler: null
s3_upload: null
tokenizer:
  tokenizer_max_length: 131072 # 65536
  tokenizer_name_or_path: /leonardo_scratch/large/userexternal/tbonomo0/models/sapienzanlp--Minerva-7B-base-recipe2
  tokenizer_revision: null
tokens:
  batch_accumulation_per_replica: 4
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 1
  sequence_length: 131072 # 65536
  train_steps: 16435
  val_check_interval: -1
